# Generated by Django 5.0 on 2024-05-26 11:53

import article_feed.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataFromForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name=150)),
                ('phone', models.IntegerField(verbose_name=11)),
                ('email', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=article_feed.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='postCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('preview_image', models.ImageField(default='products/moon.jpg', upload_to=article_feed.models.upload_to)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reportsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('excerpt', models.TextField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('preview_image', models.ImageField(default='posts/moon.jpg', upload_to=article_feed.models.upload_to)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='article_feed.postcategory')),
            ],
        ),
        migrations.CreateModel(
            name='postContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_content', models.IntegerField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Doc')])),
                ('content', models.TextField(blank=True, null=True)),
                ('order_num', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/post')),
                ('document', models.FileField(blank=True, null=True, upload_to='media/docs')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content', to='article_feed.post')),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=article_feed.models.upload_to)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article_feed.reportsgroup')),
            ],
        ),
    ]
