# Generated by Django 5.0 on 2024-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.TextField(choices=[(1, 'Блог'), (2, 'Проект')], default=1),
        ),
        migrations.DeleteModel(
            name='postContent',
        ),
    ]
