# Generated by Django 5.0 on 2024-05-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0002_postcategory_feed_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feed',
            new_name='post',
        ),
    ]
