# Generated by Django 5.0 on 2024-05-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.TextField(choices=[('Блог', 'Блог'), ('Проект', 'Проект')], default='Блог'),
        ),
    ]
