# Generated by Django 5.0 on 2024-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
