# Generated by Django 5.0 on 2024-05-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0006_postcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
