# Generated by Django 5.0 on 2024-05-09 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0006_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataFromForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name=150)),
                ('phone', models.IntegerField(verbose_name=11)),
                ('email', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='docsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='postContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='docsInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article_feed.docs')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article_feed.post')),
            ],
        ),
        migrations.AddField(
            model_name='docs',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article_feed.docstype'),
        ),
        migrations.CreateModel(
            name='postContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article_feed.post')),
                ('type_of_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article_feed.postcontenttype')),
            ],
        ),
    ]
