# Generated by Django 5.0 on 2024-05-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0007_datafromforms_docs_docstype_postcontenttype_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
