# Generated by Django 5.0 on 2024-05-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0007_alter_post_slug_alter_postcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
