# Generated by Django 5.0 on 2024-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsgroup',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
