# Generated by Django 5.0 on 2024-05-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0008_remove_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='article_feed.postcategory'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='article_feed.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='type_of_content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='article_feed.postcontenttype'),
            preserve_default=False,
        ),
    ]
