# Generated by Django 5.0 on 2024-05-18 19:18

import article_feed.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0009_alter_post_category_alter_postcontent_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(default='posts/moon.jpg', upload_to=article_feed.models.upload_to),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='article_feed.post'),
        ),
    ]
