# Generated by Django 5.0 on 2024-05-18 20:18

import article_feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0010_remove_post_excerpt_post_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='path',
            field=models.FileField(default='posts/test.pdf', upload_to=article_feed.models.upload_to),
        ),
    ]
