# Generated by Django 5.0 on 2024-05-18 20:52

import article_feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0013_products_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='path',
            field=models.FileField(default='docs/test.pdf', upload_to=article_feed.models.docs_upload_to),
        ),
        migrations.AlterField(
            model_name='products',
            name='preview_image',
            field=models.ImageField(default='products/moon.jpg', upload_to=article_feed.models.products_upload_to),
        ),
    ]
