# Generated by Django 5.0 on 2024-05-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0014_alter_docs_path_alter_products_preview_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='path',
            new_name='file',
        ),
    ]
