# Generated by Django 5.0 on 2024-05-18 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0015_rename_path_docs_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postcontent',
            name='order_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article_feed.post'),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='type_of_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='article_feed.postcontenttype'),
        ),
    ]
