# Generated by Django 5.0 on 2024-05-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_feed', '0016_postcontent_content_postcontent_order_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content', to='article_feed.post'),
        ),
    ]
